POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11dXRvc0BlbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjQ4MDMzOTk3fQ.sTn7kdeNvLLzIG9l-GHbhXyfANNhaBSTCwyO8RaFSGQ

{
    "author": "testauthor",
    "url": "testurl",
    "title": "testtitle",
    "year": 2022
}